version: '3.8'

services:
  mysql-test:
    image: mysql:8
    container_name: mysql-test
    ports:
      - 13307:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_HOST: '%'
  resdis-test:
    image: redis:alpine
    container_name: redis-test
    ports:
      - 16380:6379
    restart: on-failure